### ISSUE TITLE
Ecu tweaker is constantly stopped on Android system...

### ISSUE THREAD

**Issue by ssadicc** [cedricp/ddt4all#308]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'long b.a.a.a.g$a.b' on a null object reference
	at b.a.a.a.g.c(Unknown Source:9)
	at b.a.a.a.g.b(Unknown Source:0)
	at b.a.a.a.b.a(Unknown Source:191)
	at org.quark.dr.canapp.MainActivity$a.a(Unknown Source:27)
	at org.quark.dr.canapp.MainActivity$a.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by ssadicc** [comment]
What's the wrong?

**Comment by AndyIreland** [comment]
I just come across this myself today . I am pretty sure ecu tweaker worked fine on my xiaomi redmi note 5 pro .. but then that phone broke and my mobile phone provider then supplied me with a redmi note 6 pro and i tried loading ECU tweaker today and then it said it keeps stopping and came up with this:

java.lang.RuntimeException: java.lang.NoSuchMethodException: getSupportedDevices []
	at b.a.a.b.a.e.a(Unknown Source:91)
	at b.a.a.b.a.i.a(Unknown Source:7)
	at b.a.a.b.a.i.b(Unknown Source:2)
	at org.quark.dr.canapp.h.a(Unknown Source:27)
	at org.quark.dr.canapp.MainActivity.z(Unknown Source:175)
	at org.quark.dr.canapp.MainActivity.b(Unknown Source:0)
	at org.quark.dr.canapp.k.run(Unknown Source:18)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
Caused by: java.lang.NoSuchMethodException: getSupportedDevices []
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at b.a.a.b.a.e.a(Unknown Source:5)
	... 8 more

![ecu tweaker](https://user-images.githubusercontent.com/49172217/71549338-c9380d00-29b3-11ea-90eb-3da585a73007.jpg)

**Comment by ssadicc** [comment]
Firstly,
Thanks for answering
Yes I have this problem with my note 6 pro

java.lang.RuntimeException: An error occurred while executing
doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'long
b.a.a.a.g$a.b' on a null object reference
at b.a.a.a.g.c(Unknown Source:9)
at b.a.a.a.g.b(Unknown Source:0)
at b.a.a.a.b.a(Unknown Source:191)
at org.quark.dr.canapp.MainActivity$a.a(Unknown Source:27)
at org.quark.dr.canapp.MainActivity$a.doInBackground(Unknown Source:2)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more


What should we do about it?
Can you direct me?


28 Ara 2019 Cmt 23:51 tarihinde AndyIreland <notifications@github.com> şunu
yazdı:

**Comment by smail2133** [comment]
No way ?

**Comment by cedricp** [comment]
Can you give me the stacktrace with this version with debug symbols ?
https://drive.google.com/file/d/1mN_0ftiYFwC4l7XTWhFOJK2WdKgxz6BP/view?usp=sharing

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
