### ISSUE TITLE
ddt4all v2.0: crashes on ecu scan with dacia ecu.zip from 05.01.2019

### ISSUE THREAD

**Issue by jneuhauser** [cedricp/ddt4all#510]
Hello,

I'm using ddt4all on arch linux with OBDLink LX for my Dacia Dokker with the dacia ecu.zip from 05.01.2019.
If i do a scan for available ecu's, ddt4all crashes with the following exception:

```
Initilizing ELM with speed 115200...
Trying to open port/dev/rfcomm0 @ 115200
Serial<id=0x7f4b54d05c40, open=True>(port='/dev/rfcomm0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=5, xonxoff=False, rtscts=False, dsrdtr=False)
145 loaded ECUs in database.
Scanning ECU b'ABS-VDC - ABS-ESP'
Scanning ECU b'UCH'
Scanning ECU b'Airbag-SRS'
Traceback (most recent call last):
  File "/home/johann/dev/ddt4all/ddt4all/ddt4all.py", line 131, in scanselvehicle
    self.parent().parent().scan_project(project)
  File "/home/johann/dev/ddt4all/ddt4all/ddt4all.py", line 719, in scan_project
    self.ecu_scan.scan(self.progressstatus, self.infostatus, project)
  File "/home/johann/dev/ddt4all/ddt4all/ecu.py", line 1621, in scan
    if not self.identify_new(addr, label):
  File "/home/johann/dev/ddt4all/ddt4all/ecu.py", line 1569, in identify_new
    self.check_ecu2(diagversion, supplier, soft, soft_version, label, addr, "CAN")
  File "/home/johann/dev/ddt4all/ddt4all/ecu.py", line 1726, in check_ecu2
    elif target.checkApproximate(diagversion, supplier, soft, addr):
  File "/home/johann/dev/ddt4all/ddt4all/ecu.py", line 1166, in checkApproximate
    if self.supplier.strip() != supplier.strip():
AttributeError: 'filter' object has no attribute 'strip'
```
Does anyone have any pointers to debug and fix this issue?

Greets, Johann

**Comment by jneuhauser** [comment]
Tested master today and the issue is gone away.
