### ISSUE TITLE
Yardım ddt4all başlamadı hata

### ISSUE THREAD

**Issue by Maxilluvia** [cedricp/ddt4all#924]
Traceback (most recent call last):
  File ".\ddt4all.py", line 33, in <module>
    import parameters, ecu
  File "C:\Program Files (x86)\ddt4all\parameters.py", line 12, in <module>
    import PyQt5.QtCore as core
ImportError: No module named PyQt5.QtCore

C:\Program Files (x86)\ddt4all>

**Comment by Furtif** [comment]
you not have dependecies ok ``` No module named PyQt5.QtCore``` reinstall app
