### ISSUE TITLE
Error at startup with ubuntu

### ISSUE THREAD

**Issue by vrobert78** [cedricp/ddt4all#98]
I am on Ubuntu 18.04.

When i click on "Mode connecté" i have this error:

```
Utilisation de la base de donnée personnelle
libpng warning: iCCP: known incorrect sRGB profile
Initialisation ELM a la vitesse 38400...
Tentative d'ouverture du port/dev/ttyUSB0 @ 38400
Traceback (most recent call last):
  File "ddt4all.py", line 1329, in <module>
    options.elm = elm.ELM(options.port, port_speed, pc.isels)
  File "/data/ddt4all/elm.py", line 590, in __init__
    self.port = Port(portName, s, self.portTimeout, isels)
  File "/data/ddt4all/elm.py", line 326, in __init__
    print _("Error:") + str(e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 77: ordinal not in range(128)
```

Same issue on ubuntu 14.04.

**Comment by cedricp** [comment]
You shouldn't do that, try that : 
https://askubuntu.com/questions/112568/how-do-i-allow-a-non-default-user-to-use-serial-device-ttyusb0
